# Generated by Django 2.1.7 on 2019-03-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APItest',
        ),
    ]
