# Generated by Django 2.1.7 on 2019-03-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0004_auto_20190313_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MemberInfo',
        ),
    ]
