# Generated by Django 2.1.7 on 2019-03-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0005_auto_20190313_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='busline',
        ),
    ]
