# Generated by Django 2.1.8 on 2019-05-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0006_delete_busline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opendi', models.CharField(blank=True, max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
