# Generated by Django 2.1.8 on 2019-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0008_auto_20190507_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
