# Generated by Django 2.1.8 on 2019-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0009_user_info_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_offer',
            name='breakfast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='dinner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='lunch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='openid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
