# Generated by Django 2.1.8 on 2019-06-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0010_auto_20190530_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_offer',
            old_name='end_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='meal_offer',
            name='start_date',
        ),
    ]
