# Generated by Django 2.1.8 on 2019-06-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0011_auto_20190603_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_offer',
            name='line',
        ),
        migrations.RemoveField(
            model_name='meal_offer',
            name='openid',
        ),
        migrations.RemoveField(
            model_name='meal_offer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='meal_offer',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xxb.user_info'),
        ),
    ]
