# Generated by Django 2.1.8 on 2019-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0012_auto_20190617_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_offer',
            name='breakfast',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meal_offer',
            name='dinner',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meal_offer',
            name='lunch',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
