# Generated by Django 2.1.8 on 2019-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0013_auto_20190624_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_offer',
            name='order_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
