# Generated by Django 2.1.8 on 2019-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0014_auto_20190624_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_offer',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
