# Generated by Django 2.1.8 on 2019-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0015_auto_20190624_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='gps_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gprs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('onboard_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nextstop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('server_time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='station_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gprs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
