# Generated by Django 2.1.8 on 2019-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0016_gps_info_station_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_info',
            name='server_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
