# Generated by Django 2.1.8 on 2019-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0018_auto_20190625_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
