# Generated by Django 2.1.8 on 2019-06-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0019_auto_20190625_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gps_info',
        ),
    ]
