# Generated by Django 2.1.8 on 2019-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0021_gps_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='week_menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_day', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('breakfast', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lunch', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dinner', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
