# Generated by Django 2.1.8 on 2019-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0022_week_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_time', models.DateTimeField(auto_now=True, null=True)),
                ('edit_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('edit_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('breakfast', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lunch', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dinner', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
