# Generated by Django 2.1.8 on 2019-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0023_edit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_log',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
