# Generated by Django 2.1.8 on 2019-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0025_auto_20190902_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='strong_mileage_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('car_num', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('YunYingRiQi', models.DateField(blank=True, null=True)),
                ('today_mileage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_mileage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data_create_time', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
