# Generated by Django 2.1.8 on 2019-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0026_strong_mileage_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='gps_info_backup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gprs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('onboard_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nextstop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('server_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
