# Generated by Django 2.1.8 on 2019-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0028_gprsid_to_busline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSite_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RoadID', models.CharField(blank=True, max_length=255, null=True)),
                ('RoadName', models.CharField(blank=True, max_length=255, null=True)),
                ('RoadType', models.CharField(blank=True, max_length=255, null=True)),
                ('SiteID', models.CharField(blank=True, max_length=255, null=True)),
                ('SiteNo', models.CharField(blank=True, max_length=255, null=True)),
                ('SiteName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
