# Generated by Django 2.1.8 on 2019-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0031_roadid_to_busline_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadid_to_busline',
            name='Rank',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
