# Generated by Django 2.1.8 on 2019-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0035_roadid_to_busline_line_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadID_to_BusLine_new',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RoadID', models.CharField(blank=True, max_length=255, null=True)),
                ('BusLine', models.CharField(blank=True, max_length=255, null=True)),
                ('RoadType', models.CharField(blank=True, max_length=255, null=True)),
                ('Line_info', models.CharField(blank=True, max_length=255, null=True)),
                ('Rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
