# Generated by Django 2.1.8 on 2019-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0037_c_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_count',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ip_adress', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('web_traffic', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
