# Generated by Django 2.1.8 on 2019-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxb', '0038_traffic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_count',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
